add
AndreyReset/java-explore-with-me pull request #1
Opened 2022-10-14 14:37 UTC by AndreyReset

2022-10-14 15:40 UTC, AndreyReset commented
Евгений, добрый день/вечер!
В проекте три модуля
1. Gateway
2. Server
3. Stat

На локальном компьютере у меня был еще один модуль-библиотека library. В этот модуль у меня были включены общие классы и дто, которые идут на вход от пользователя. 
При попытке все это загрузить на гит у меня благополучно не вышло. Кастомная библиотека была подключена через зависимость к родительскому пом файлу. На гите все это не стартовало, он не понимал откуда брать данные. Как вариант можно было бы загрузить все это на репозиторий мавена (либо сделать что-то подобное на гите) и подключить.. Я обязательно так попробую, но выбрал более простое решение, т.к. время особо не позволяет. В каждом модуле есть папка lib. В этой папке находятся файлы из кастомной библиотеки. Просьба рассматривать эту папку как отдельный модуль (именно так, как задумывалось).

Что касается тестов постман - старые тесты проходят, по новым одна ошибка. По информации от наставника это не должно помешать прохождению ревью.

2022-10-15 06:42 UTC, eugene-lenkevich requested changes
Привет, Андрей, спасибо за PR

Первым делом поздравляю тебя с тем, что ты дошел до дипломной работы, ты крут без вариантов :)

Далее, 
наша цель в том, чтобы сделать красоту в этом проекте, все таки диплом, вдруг по нему оценивать навыки будут.  Я оставил кучку коментариев, будут вопросы, задавай в слаке, не стесняйся, немножко допилить осталось :)

Удачи!

2022-10-15 06:42 UTC, eugene-lenkevich commented on gateway/src/main/java/explorewithme/lib/exception/ErrorHandlerGateway.java
> +        log.info(String.valueOf(errorResponse(e, HttpStatus.BAD_REQUEST)));
Два раза строчка errorResponse(e, HttpStatus.BAD_REQUEST), может ее  в переменную? :)

2022-10-15 06:42 UTC, eugene-lenkevich commented on gateway/src/main/java/explorewithme/lib/exception/ErrorResponse.java
> +    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
Давай попробуем настроить фоматы даты и времени глобально, чтобы не приходилось вот так везде аннотациями это указывать :)

https://www.baeldung.com/spring-boot-formatting-json-dates

2022-10-15 06:42 UTC, eugene-lenkevich commented on server/src/main/java/explorewithme/lib/util/DataToLine.java
> +    public static <T> String arrToLine(Optional<T[]> data) {
Если почитать джавадок от Optional то там написано что он предназначен для того, чтобы возвращать результат, который может быть пустым. В качестве параметра от него особо толку нет, на null все равно надо проверять, но создается лишний объект который потом собирать сборщику мусора плюс синтаксически конструкция более громоздкая:)

2022-10-15 06:42 UTC, eugene-lenkevich commented on server/src/main/java/explorewithme/lib/util/ValidDateTime.java
> +public class ValidDateTime {
Не уверен что название соответвует тому что класс делает, может назвать DateTimeUtils? :)

2022-10-15 06:42 UTC, eugene-lenkevich commented on server/src/main/java/explorewithme/model/Category.java
> +public class Category {
Лучше переопределить equals и hashCode для всех сущностей, причем на основе первичного ключа - id в данном случае :)
 
Вообще, сущность - это не просто объект, это представление строки таблицы базы данных, а строку таблицы однозначно определяет ее идентификатор, и потому, соотвественно, для сущностей equals и hashCode стоит определять на основе  id (первичного ключа). 

Остальные поля, при этом, могут вообще быть разными, то есть могут существовать разные версии одного и того же объекта, но как это разруливатеся - это уже отдельная история.
 
https://habr.com/ru/post/268903/

2022-10-15 06:42 UTC, eugene-lenkevich commented on server/src/main/java/explorewithme/model/Compilation.java
> +    @ManyToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
Не уверен что стоит тут использовать EAGER в данном случае :)
Все свзязанные записи ведь будут вытаскиваться при каждом запросе к таблице независимо от того нужны они или нет, в итоге получается сложный запрос с лдойнами. Лучше все таки оставлять связи LAZY, но, да, в этом этом случае, мы будем порлучать проблему N+1 запросов. Для того чтобы избавится от этой пробелмы мы можем явно указывать в конкретном запросе что надо вытащить еще и связанные оленивые коллекции с помощью join fetch

![image](https://user-images.githubusercontent.com/94845100/194059305-413c94fd-e9da-40d1-8090-05568e0cc255.png)


https://stackoverflow.com/questions/17431312/what-is-the-difference-between-join-and-join-fetch-when-using-jpa-and-hibernate

Или еще вот, entity graph
https://sysout.ru/entity-graph-v-spring-data-jpa/

2022-10-15 06:42 UTC, eugene-lenkevich commented on server/src/main/java/explorewithme/model/Event.java
> +    @ManyToOne(cascade = CascadeType.ALL)
Вот тут, кстати, fetchType=EAGER стоит по умлочанию, это считается нормальным потому что связана одна запись а не коллекция :)

2022-10-15 06:42 UTC, eugene-lenkevich commented on server/src/main/java/explorewithme/model/Event.java
> +    @ManyToMany(fetch = FetchType.LAZY, mappedBy = "events")
А тут fetch = FetchType.LAZY по умолчанию, модно не писать лишний раз :)

2022-10-15 06:42 UTC, eugene-lenkevich commented on server/src/main/java/explorewithme/p_admin/compilation/AdminCompilationServiceImpl.java
> +@Transactional(readOnly = true)
На самом деле можно и без транзакций запускать поисковые методы, транзакция тут нужна для тонкой настройки в зависимости от урованя изоляции чтобы например избежать фантомных чтений. А иначе это лишние накладные расходы на транзакции для операций чтения :)
Но это не касается операций изменения данных, там это оправдано. Но ты можешь оставить все как есть, я подсветил этот момент чтобы он остался в памяти, потом можешь поразбираться, но, вообще, это сложная и обширная тема :)

2022-10-15 06:42 UTC, eugene-lenkevich commented on server/src/main/java/explorewithme/p_admin/compilation/AdminCompilationServiceImpl.java
> +        repository.save(compilation);
Какой инересный метод удаления :)
А просто через чтото вроде deleteByIdAndCompilationId разве не подоходит... пересохранять все сущности ради удаления одной записи?)

2022-10-15 06:42 UTC, eugene-lenkevich commented on server/src/main/java/explorewithme/repository/CompilationRepository.java
> +@Repository
Эту аннотацию вроде как уже можно и не писать :)

2022-10-15 06:46 UTC, eugene-lenkevich commented
> На локальном компьютере у меня был еще один модуль-библиотека library. В этот модуль у меня были включены общие классы и дто, которые идут на вход от пользователя. 

Ну, без ошибки ничего не понятно, но, вообще, в микросервисной архитектцре ничего стращного на самом деле нет в том чтобы код дублировался. По факту это даже не дублирование, просто в какой то момент времени реализации совпадают :)
Пусть сервисы будут независимыми, чем меньше общих библиотек, то есть жестких связей, тем лучше (но без фанатизма, конечно)


> Что касается тестов постман - старые тесты проходят, по новым одна ошибка. По информации от наставника это не должно помешать прохождению ревью.

Спасибо что предупредил :)

2022-10-15 09:21 UTC, AndreyReset commented on gateway/src/main/java/explorewithme/lib/exception/ErrorHandlerGateway.java
> +        log.info(String.valueOf(errorResponse(e, HttpStatus.BAD_REQUEST)));
повторение убрал в переменную

2022-10-15 09:25 UTC, AndreyReset commented on server/src/main/java/explorewithme/lib/util/ValidDateTime.java
> +public class ValidDateTime {
согласен) переименовал

2022-10-15 09:43 UTC, AndreyReset commented on server/src/main/java/explorewithme/model/Event.java
> +    @ManyToMany(fetch = FetchType.LAZY, mappedBy = "events")
убрал

2022-10-15 09:45 UTC, AndreyReset commented on server/src/main/java/explorewithme/repository/CompilationRepository.java
> +@Repository
убрал)

2022-10-15 09:47 UTC, AndreyReset commented on server/src/main/java/explorewithme/model/Category.java
> +public class Category {
готово

2022-10-15 12:42 UTC, AndreyReset commented on server/src/main/java/explorewithme/lib/util/DataToLine.java
> +    public static <T> String arrToLine(Optional<T[]> data) {
из модуля server и вовсе убрал этот файл. но в модуле gateway поправил

2022-10-15 12:43 UTC, AndreyReset commented on server/src/main/java/explorewithme/lib/util/ValidDateTime.java
> +public class ValidDateTime {
также из модуля server убрал данный файл

2022-10-15 12:51 UTC, AndreyReset commented on gateway/src/main/java/explorewithme/lib/exception/ErrorResponse.java
> +    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
создал новый класс config
добавил переменную в application.properties

2022-10-15 13:07 UTC, AndreyReset commented on server/src/main/java/explorewithme/model/Compilation.java
> +    @ManyToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
готово

2022-10-15 13:08 UTC, AndreyReset commented on server/src/main/java/explorewithme/p_admin/compilation/AdminCompilationServiceImpl.java
> +@Transactional(readOnly = true)
пока оставил как есть

2022-10-15 16:16 UTC, AndreyReset commented on server/src/main/java/explorewithme/p_admin/compilation/AdminCompilationServiceImpl.java
> +        repository.save(compilation);
оставил как было

2022-10-15 17:05 UTC, eugene-lenkevich approved these changes
Теперь все отлично, спасибо :)

2022-10-16 03:47 UTC, merged